#!/usr/bin/env python3
"""Public status page from the pulse digest (cst-j01t §5.3, ratified:
FULL digest, attention rows included — honest degradation is the demo).

Reads the latest digest from the pulse ledger (SCUTL_PULSE_STATE) and
emits status.html. Regenerated by the operator loop each period.
Usage: python site/status.py [--out site/out/status.html]
"""
from __future__ import annotations

import argparse
import html
import json
import os
from datetime import datetime, timezone
from pathlib import Path

CSS = """
body{margin:0 auto;max-width:60rem;padding:2rem 1rem;font:16px/1.55
 system-ui,sans-serif;color:#1a1a1a;background:#fbfaf8}
.ok{color:#1d5c1d}.attention{color:#8a5b00}.unreachable,.red{color:#a02020}
table{border-collapse:collapse;width:100%}
td,th{border:1px solid #ddd;padding:.4em .6em;text-align:left;vertical-align:top}
pre{background:#f0ede8;padding:1rem;border-radius:4px;white-space:pre-wrap}
.muted{color:#666}footer{margin-top:3rem;font-size:.85em;color:#666;
 border-top:1px solid #ddd;padding-top:1rem}
"""


def esc(s):
    return html.escape(str(s if s is not None else ""))


def main(argv=None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--out", default=str(Path(__file__).parent / "out" / "status.html"))
    p.add_argument("--state", default=os.environ.get(
        "SCUTL_PULSE_STATE", str(Path.home() / ".scutl" / "pulse")))
    args = p.parse_args(argv)

    log = Path(args.state) / "pulse.log"
    digests = [json.loads(l) for l in log.read_text().splitlines()
               if l.strip() and '"digest"' in l]
    digests = [d for d in digests if d.get("kind") == "digest"]
    if not digests:
        raise SystemExit("no digest in ledger")
    d = digests[-1]
    computed = d.get("computed", {})
    rows = ""
    for r in computed.get("table", []):
        state = r.get("state", "?")
        breaches = r.get("breaches") or []
        blist = ("<ul>" + "".join(f"<li>{esc(b)}</li>" for b in breaches)
                 + "</ul>") if breaches else "—"
        rows += (f"<tr><td><code>{esc(r.get('check'))}</code>"
                 f"<br><span class=muted>{esc(r.get('kind'))}</span></td>"
                 f"<td class=\"{esc(state)}\"><strong>{esc(state)}</strong></td>"
                 f"<td>{blist}</td>"
                 f"<td class=muted>{esc(r.get('observed_at',''))[:19]}Z</td></tr>")
    flags = d.get("open_flags") or computed.get("open_flags") or []
    flags_html = (", ".join(f"<code>{esc(f)}</code>" for f in flags)
                  if flags else "none")
    notes = d.get("notes", "")
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    body = f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>scutl status</title><style>{CSS}</style></head><body>
<nav><a href="index.html">scutl</a></nav>
<h1>Status</h1>
<p>This page IS the product demo: it is the latest digest composed by
the <a href="recipes/status-digest/index.html">status-digest</a> recipe,
reading the <a href="recipes/scheduled-jobs/index.html">scheduled-jobs</a>
and <a href="recipes/uptime-monitoring/index.html">uptime-monitoring</a>
recipes running live on our own infrastructure. Nothing is curated out
— attention rows and open flags render exactly as composed. A status
page that can't show its own problems can't be trusted about anything
else.</p>
<p class=muted>digest <code>{esc(d.get('id'))}</code> · period
{esc(d.get('period'))} · composed {esc(d.get('ts',''))[:19]}Z ·
page rendered {now}</p>
<table><tr><th>Check</th><th>State</th><th>Breaches (verbatim)</th>
<th>Observed</th></tr>{rows}</table>
<h2>Open anomaly flags</h2><p>{flags_html}</p>
<h2>Operator notes (verbatim)</h2><pre>{esc(notes)}</pre>
<footer>Digests every 6h; flags latch until a human clears them.</footer>
</body></html>"""
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body)
    print(f"status page: digest {d.get('id')} period {d.get('period')} -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
